name: Generate Functions
on: push
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep '_FUNC'
        env:
            FORMART_FUNC: ${{format('{0},{1}.','Hi','world')}} #format
            JOIN_FUNC: ${join(github.event.*.html_url,',')} #カンマで結合